<h1>Style Guide</h1>

<section class="sg-colors">
    <h3 class="sg-h">Colors</h3>
    <ul>
        <li class="brand-primary">
            <span></span>
            <p>Brand Primary</p>
        </li>
        <li class="brand-secondary">
            <span></span>
            <p>Brand Secondary</p>
        </li>
        <li class="brand-tertiary">
            <span></span>
            <p>Brand Tertiary</p>
        </li>
        <li class="brand-success">
            <span></span>
            <p>Brand Success</p>
        </li>
        <li class="brand-warning">
            <span></span>
            <p>Brand Warning</p>
        </li>
        <li class="brand-danger">
            <span></span>
            <p>Brand Danger</p>
        </li>
        <li class="brand-info">
            <span></span>
            <p>Brand Info</p>
        </li>
        <li class="brand-dark">
            <span></span>
            <p>Brand Dark</p>
        </li>
        <li class="brand-light">
            <span></span>
            <p>Brand Light</p>
        </li>
        <li class="brand-text">
            <span></span>
            <p>Brand Text</p>
        </li>
    </ul>
</section>

<section class="sg-typography">
    <h3 class="sg-h">Typography</h3>
    <aside class="base">
        <dl>
            <dt>Paragraph</dt>
                <dd class="sg-paragaphs"><p>Donec ullamcorper nulla non metus auctor fringilla. <a href="#">Maecenas</a> sed diam eget risus varius blandit sit amet non magna.</p></dd>
            <dt>Links</dt>
                <dd class="sg-links"><a href="#">This is a text link.</a></dd>
            <dt>Strong Text</dt>
                <dd class="sg-strong"><strong>Strong is used to indicate strong importance</strong></dd>
            <dt>Emphasis Text</dt>
                <dd class="sg-emphasis"><em>This text has added emphasis</em></dd>
        </dl>
    </aside>
    <aside class="headings">
        <ul>
            <li><h1>Heading 1</h1></li>
            <li><h2>Heading 2</h2></li>
            <li><h3>Heading 3</h3></li>
            <li><h4>Heading 4</h4></li>
            <li><h5>Heading 5</h5></li>
            <li><h6>Heading 6</h6></li>
        </ul>
    </aside>
    <aside class="unordered">
        <h4>Unordered List</h4>
        <ul>
            <li>This is a list item in an unordered list</li>
            <li>The sequence of items is not important.</li>
            <li>Lists can be nested inside of each other
                <ul>
                    <li>This is a nested list item</li>
                    <li>This is another nested list item</li>
                </ul>
            </li>
            <li>This is the last list item</li>
        </ul>
    </aside>
    <aside class="ordered">
        <h4>Ordered List</h4>
        <ol>
            <li>This is a list item in an ordered list</li>
            <li>The sequence of items is important.</li>
            <li>Lists can be nested inside of each other
                <ol>
                    <li>This is a nested list item</li>
                    <li>This is another nested list item</li>
                </ol>
            </li>
            <li>This is the last list item</li>
        </ol>
    </aside>
    <aside class="bq">
        <h4>Block Quote</h4>
        <blockquote>Nullam id dolor id nibh ultricies vehicula ut id elit.</blockquote>
    </aside>
</section>

<section class="sg-button">
    <h3 class="sg-h">Buttons</h3>
    <ul>
        <li>
            <small>Primary Button</small>
            <span class="source"><button class="button"><span><span>Primary</span></span></button></span>
        </li>
        <li>
            <small>Primary Button Small</small>
            <span class="source"><button class="button btn-small"><span><span>Primary</span></span></button></span>
        </li>
        <li>
            <small>Primary Button Anchor</small>
            <span class="source"><a class="button"><span>Primary</span></a></span>
        </li>

        <li>
            <small>Secondary Button</small>
            <span class="source"><button class="button button-secondary"><span><span>Secondary</span></span></button></span>
        </li>
        <li>
            <small>Secondary Button Small</small>
            <span class="source"><button class="button btn-small button-secondary"><span><span>Secondary</span></span></button></span>
        </li>
        <li>
            <small>Secondary Button Anchor</small>
            <span class="source"><a class="button button-secondary"><span>Secondary</span></a></span>
        </li>
        <li>
            <small>Add to Cart</small>
            <span class="source"><button class="button btn-cart"><span><span>Add to Cart</span></span></button></span>
        </li>
        <li>
            <small>Add to Cart Small</small>
            <span class="source"><button class="button btn-small btn-cart"><span><span>Add to Cart</span></span></button></span>
        </li>
        <li>
            <small>Add to Cart Anchor</small>
            <span class="source"><a class="button btn-cart"><span>Add to Cart</span></a></span>
        </li>

        <li>
            <small>Checkout Continue Button</small>
            <span class="source"><button class="button btn-continue"><span><span>Continue</span></span></button></span>
        </li>
        <li>
            <small>Alternate Continue Button</small>
            <span class="source"><button class="button btn-continue button-secondary"><span><span>Continue</span></span></button></span>
        </li>

        <li>
            <small>Proceed to Checkout Button</small>
            <span class="source"><button type="button" title="Proceed to Checkout" class="button btn-proceed-checkout btn-checkout"><span><span>Proceed to Checkout</span></span></button></span>
        </li>
        <li>
            <small>Clear Shopping Cart Button</small>
            <span class="source"><button type="submit" name="update_cart_action" value="empty_cart" title="Clear Shopping Cart" class="button btn-empty button-secondary" id="empty_cart_button"><span><span>Clear Shopping Cart</span></span></button></span>
        </li>
        <li>
            <small>Update Shopping Cart Button</small>
            <span class="source"><button type="submit" name="update_cart_action" value="update_qty" title="Update Shopping Cart" class="button btn-update button-secondary"><span><span>Update Shopping Cart</span></span></button></span>
        </li>
        <li class="cart">
            <small>Continue Shopping Button</small>
            <span class="source"><button type="button" title="Continue Shopping" class="button btn-continue"><span><span>Continue Shopping</span></span></button></span>
        </li>
        <li>
            <small>Checkout Back Button</small>
            <span class="source"><p class="back-link"><a href="#"><small>« </small>Back</a></p></span>
        </li>
    </ul>
</section>

<section class="sg-form">
    <h3 class="sg-h">Forms</h3>
    <form>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="sg-text" class="required"><em>*</em>Text Input</label>
                    <div class="input-box"><input name="sg-text" type="text" class="input-text required-entry" /></div>
                </div>
                <div class="field">
                    <label for="sg-text-placeholder" class="required"><em>*</em>Placeholder Input</label>
                    <div class="input-box"><input name="sg-text" type="text" class="input-text required-entry" placeholder="Placeholder" /></div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="sg-text-error" class="required"><em>*</em>Email Input - Validation Error</label>
                    <div class="source"><div class="input-box validation-error"><input name="sg-text" type="email" class="input-text required-entry validation-failed" /><div class="validation-advice">Please enter a valid email address. For example johndoe@domain.com.</div></div></div>
                </div>
                <div class="field">
                    <label for="sg-text-passed" class="required"><em>*</em>Email Input - Validation Passed</label>
                    <div class="source"><div class="input-box validation-passed"><input name="sg-text" type="email" class="input-text required-entry validation-passed" /></div></div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="sg-text-tel" class="required"><em>*</em>Password Input</label>
                    <div class="input-box"><input name="sg-text-tel" type="password" value="abcdefg" class="input-text required-entry" /></div>
                </div>
                <div class="field">
                    <label for="sg-text-tel" class="required"><em>*</em>Telephone Input</label>
                    <div class="input-box"><input name="sg-text-tel" type="tel" value="843-412-7401" class="input-text required-entry" /></div>
                </div>
            </li>
            <li class="wide">
                <label for="sg-disabled">Text Input - Disabled</label>
                <div class="input-box"><input name="sg-disabled" type="text" disabled="disabled" class="input-text" /></div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="sg-tel" class="required">Telephone Input <small>Also good for Credit Card Inputs</small></label>
                    <div class="input-box"><input name="sg-tel" type="tel" class="input-text" /></div>
                </div>
            </li>
            <li class="control">
                <div class="source"><input type="radio" class="radio" id="custom-radio1" name="custom-radio" /><label for="custom-radio1">Custom Radio</label></div>
            </li>
            <li class="control">
                <div class="source"><input type="radio" class="radio" id="custom-radio2" name="custom-radio"  checked="checked" /><label for="custom-radio2">Custom Radio Active</label></div>
            </li>
            <li class="control">
                <div class="source"><input type="radio" class="radio" id="custom-radio3" name="custom-radio"  disabled="disabled" /><label for="custom-radio3">Custom Radio Disabled</label></div>
            </li>
            <li class="control">
                <div class="source"><input type="checkbox" class="checkbox" id="custom-checkbox1" name="custom-checkbox" /><label for="custom-checkbox1">Custom Checkbox</label></div>
            </li>
            <li class="control">
                <div class="source"><input type="checkbox" class="checkbox" id="custom-checkbox2" name="custom-checkbox" checked="checked" /><label for="custom-checkbox2">Custom Checkbox Active</label></div>
            </li>
            <li class="control">
                <div class="source"><input type="checkbox" class="checkbox" id="custom-checkbox3" name="custom-checkbox" disabled="disabled" /><label for="custom-checkbox3">Custom Checkbox Disabled</label></div>
            </li>
            <li class="control">
                <div class="source"><input type="radio" class="radio no-style" id="noncustom-radio1" name="noncustom-radio" /><label for="noncustom-radio1">Non-Custom Radio</label></div>
            </li>
<li class="control">
                <div class="source"><input type="checkbox" class="checkbox no-style" id="noncustom-checkbox1" name="noncustom-checkbox" /><label for="noncustom-checkbox1">Non-Custom Checkbox</label></div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="custom-select" class="required"><em>*</em>Custom Select</label>
                    <div class="input-box">
                        <select id="custom-select" name="custom-select" title="Custom Select" class="validate-select required-entry">
                            <option value="">Please select a Ninja Turtle, or Character</option>
                            <option value="1">Leonardo</option>
                            <option value="2">Michelangelo</option>
                            <option value="3">Donatello</option>
                            <option value="999">Raphael</option>
                            <option value="4">Splinter</option>
                            <option value="5">April O'Neil</option>
                            <option value="6">Casey Jones</option>
                            <option value="7">Shredder</option>
                            <option value="8">Karai</option>
                        </select>
                    </div>
                </div>
                <div class="field">
                    <label for="custom-select" class="required"><em>*</em>Custom Select - Validation Error</label>
                    <div class="input-box validation-error">
                        <select id="custom-select" name="custom-select" title="Custom Select" class="validate-select required-entry validation-failed">
                            <option value="">Would you like to know more?</option>
                            <option value="1">Yes</option>
                            <option value="3">The only good bug, is a dead bug.</option>
                        </select>
                        <div class="validation-advice">Please select an option.</div>
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="custom-select" class="required"><em>*</em>Custom Select Small</label>
                    <div class="input-box">
                        <select id="custom-select" name="custom-select" title="Custom Select" class="validate-select required-entry small-select">
                            <option value="">---</option>
                            <option value="0">No</option>
                            <option value="1">Yes</option>
                        </select>
                    </div>
                </div>
                <div class="field">
                    <label for="unstyled-select" class="required"><em>*</em>Non-Custom Select</label>
                    <div class="input-box">
                        <select id="unstyled-select" name="custom-select" title="Custom Select" class="validate-select required-entry no-style">
                            <option value="">---</option>
                            <option value="0">No</option>
                            <option value="1">Yes</option>
                        </select>
                    </div>
                </div>
            </li>
        </ul>
    </form>
</section>

<section class="sg-messages">
    <h3 class="sg-h">Messages</h3>

    <small>Success Message</small>
    <ul class="messages">
        <li class="success-msg">
            <ul>
                <li><span>Ink Eater: Krylon Bombear Destroyed Tee was added to your shopping cart.</span></li>
            </ul>
        </li>
    </ul>

    <small>Error Message</small>
    <ul class="messages">
        <li class="error-msg">
            <ul>
                <li><span>There was a problem with the subscription: This email address is already assigned to another user.</span></li>
            </ul>
        </li>
    </ul>

    <small>Notice Message</small>
    <ul class="messages">
        <li class="notice-msg">
            <ul>
                <li><span>There was a problem with the subscription: This email address is already assigned to another user.</span></li>
            </ul>
        </li>
    </ul>
</section>
