<h1>Super Select</h1>

<section class="sg-form">
    <h3 class="sg-h">Forms</h3>
    <form>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="custom-select" class="required"><em>*</em>Thumbnail Select</label>
                    <div class="input-box">
                        <select id="custom-select" name="custom-select" title="Custom Select" class="validate-select required-entry ba-thumbnail">
                            <option value="" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/logo.png') ?>">Please select a Ninja Turtle, or Character</option>
                            <option value="1" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/leo.png') ?>">Leonardo</option>
                            <option value="2" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/mike.png') ?>">Michelangelo</option>
                            <option value="3" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/don.png') ?>">Donatello</option>
                            <option value="999" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/raph.png') ?>">Raphael</option>
                            <option value="4" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/splinter.png') ?>">Splinter</option>
                            <option value="5" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/april.png') ?>">April O'Neil</option>
                            <option value="6" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/cj.png') ?>">Casey Jones</option>
                            <option value="7" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/shredder.png') ?>">Shredder</option>
                            <option value="8" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/karai.png') ?>">Karai</option>
                            <option value="10" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/baxter-stockman.png') ?>">Baxter</option>
                            <option value="11" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/krang.png') ?>">Krang</option>
                            <option value="12" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/beabop.png') ?>">Beabop</option>
                            <option value="13" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/rocksteady.png') ?>">Rocksteady</option>
                            <option value="14" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/leatherhead.png') ?>">Leatherhead</option>
                        </select>
                    </div>
                </div>
                <div class="field">
                    <label for="custom-select" class="required"><em>*</em>Custom Select - Validation Error</label>
                    <div class="input-box validation-error">
                        <select id="custom-select" name="custom-select" title="Custom Select" class="validate-select required-entry validation-failed">
                            <option value="">Would you like to know more?</option>
                            <option value="1">Yes</option>
                            <option value="3">The only good bug, is a dead bug.</option>
                        </select>
                        <div class="validation-advice">Please select an option.</div>
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="">Custom Select - Right</label>
                    <div class="input-box">
                        <select name="custom-select-right" class="ba-right" id="custom-select-right">
                            <option value="1">Select Magento Version</option>
                            <option value="2">Enterprise Edition 1.13</option>
                            <option value="3">Community Edition 1.8</option>
                        </select>
                    </div>
                </div>
                <div class="field">
                    <label for="">Custom Select - Left</label>
                    <div class="input-box">
                        <select name="custom-select-left" id="custom-select-left" class="ba-left">
                            <option value="1" selected>Select Magento Version</option>
                            <option value="2">Enterprise Edition 1.13</option>
                            <option value="3">Community Edition 1.8</option>
                            <option value="2">Enterprise Edition 1.14</option>
                            <option value="3">Community Edition 1.9</option>
                        </select>
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="">Custom Select - Under</label>
                    <div class="input-box">
                        <select name="custom-select-left" class="ba-under" id="custom-select-left">
                            <option value="1" selected>Select Magento Version</option>
                            <option value="2">Enterprise Edition 1.13</option>
                            <option value="3">Community Edition 1.8</option>
                            <option value="2">Enterprise Edition 1.14</option>
                            <option value="3">Community Edition 1.9</option>
                        </select>
                    </div>
                </div>
                <div class="field">
                    <label for="">Custom Select - Overlay</label>
                    <div class="input-box">
                        <select name="custom-select-right" class="ba-overlay" id="custom-select-right">
                            <option value="1">Select Magento Version</option>
                            <option value="2">Enterprise Edition 1.13</option>
                            <option value="3">Community Edition 1.8</option>
                            <option value="2">Enterprise Edition 1.14</option>
                            <option value="3">Community Edition 1.9</option>
                        </select>
                    </div>
                </div>
                <div class="field">
                    <label for="">Custom Select - Fullscreen</label>
                    <div class="input-box">
                        <select name="custom-select-right" class="ba-fullscreen" id="custom-select-right">
                            <option value="1">Select Magento Version</option>
                            <option value="2">Enterprise Edition 1.13</option>
                            <option value="3">Community Edition 1.8</option>
                            <option value="2">Enterprise Edition 1.14</option>
                            <option value="3">Community Edition 1.9</option>
                        </select>
                    </div>
                </div>
                <div class="field">
                    <label for="custom-select" class="required"><em>*</em>Fullscreen Thumbnail Select</label>
                    <div class="input-box">
                        <select id="custom-select" name="custom-select" title="Custom Select" class="validate-select required-entry ba-fullthumb">
                            <option value="" data-color="#fff">Pick Your Favorite Color</option>
                            <option value="1" data-color="#4A90E2">Leonardo</option>
                            <option value="2" data-color="#F5A623">Michelangelo</option>
                            <option value="3" data-color="#9013FE">Donatello</option>
                            <option value="999" data-color="#D0021B">Raphael</option>
                            <option value="4" data-color="#8B572A">Splinter</option>
                            <option value="5" data-color="#F8E71C">April O'Neil</option>
                            <option value="6" data-color="#B8E986">Casey Jones</option>
                            <option value="7" data-color="#9B9B9B">Shredder</option>
                            <option value="8" data-color="#003263">Karai</option>
                            <option value="10" data-color="#B09CBD">Baxter</option>
                            <option value="11" data-color="#D6A2AA">Krang</option>
                            <option value="12" data-color="#933123">Beabop</option>
                            <option value="13" data-color="#9B9B9B">Rocksteady</option>
                            <option value="14" data-color="#14B97F">Leatherhead</option>
                        </select>
                    </div>
                </div>
            </li>
            <li class="wide">
                <label for="custom-select" class="required"><em>*</em>Custom Select Wide &amp; Long</label>
                <div class="input-box">
                    <select id="custom-select" name="custom-select" title="Custom Select" class="validate-select required-entry">
                        <option value="">When I grow up I want to be...</option>
                        <option value="lifetime">Robert Benson</option>
                        <option value="1">Ron Burgundy.</option>
                        <option value="2">Ashley Schaeffer.</option>
                        <option value="3">Bob Oblong.</option>
                        <option value="4">Chazz Michael Michaels.</option>
                        <option value="5">Ricky Bobby!</option>
                        <option value="6">Frank "The Tank" Richard.</option>
                        <option value="1">Mugatu.</option>
                        <option value="2">Lord Business.</option>
                        <option value="3">Armando.</option>
                        <option value="4">Deangelo Vickers.</option>
                        <option value="5">Megamind!</option>
                        <option value="6">Allen Gamble.</option>
                        <option value="1">Dr. Rick Marshall.</option>
                        <option value="2">Brennan Huff.</option>
                        <option value="3">Jakie Moon.</option>
                        <option value="4">Harold Crick.</option>
                        <option value="5">Corbit!</option>
                        <option value="6">Jack Wyatt.</option>
                        <option value="1">Buddy the Elf.</option>
                        <option value="2">Sky Corrigan.</option>
                        <option value="3">Steve Butabi.</option>
                    </select>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="custom-select" class="required"><em>*</em>Thumbnail Select - Validation Error</label>
                    <div class="input-box validation-error">
                        <select id="custom-select" name="custom-select" title="Custom Select" class="validate-select required-entry ba-thumbnail">
                            <option value="" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/logo.png') ?>">Please select a Ninja Turtle, or Character</option>
                            <option value="1" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/leo.png') ?>">Leonardo</option>
                            <option value="2" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/mike.png') ?>">Michelangelo</option>
                            <option value="3" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/don.png') ?>">Donatello</option>
                            <option value="999" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/raph.png') ?>">Raphael</option>
                            <option value="4" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/splinter.png') ?>">Splinter</option>
                            <option value="5" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/april.png') ?>">April O'Neil</option>
                            <option value="6" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/cj.png') ?>">Casey Jones</option>
                            <option value="7" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/shredder.png') ?>">Shredder</option>
                            <option value="8" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/karai.png') ?>">Karai</option>
                            <option value="10" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/baxter-stockman.png') ?>">Baxter</option>
                            <option value="11" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/krang.png') ?>">Krang</option>
                            <option value="12" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/beabop.png') ?>">Beabop</option>
                            <option value="13" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/rocksteady.png') ?>">Rocksteady</option>
                            <option value="14" data-image="<?php echo $this->getSkinUrl('images/blueacorn/super-selects/sample/leatherhead.png') ?>">Leatherhead</option>
                        </select>
                    </div>
                </div>
                <div class="field">
                    <label for="">Custom Select - Left - Validation Error</label>
                    <div class="input-box validation-error">
                        <select name="custom-select-left" id="custom-select-left" class="ba-left">
                            <option value="1" selected>Select Magento Version</option>
                            <option value="2">Enterprise Edition 1.13</option>
                            <option value="3">Community Edition 1.8</option>
                            <option value="2">Enterprise Edition 1.14</option>
                            <option value="3">Community Edition 1.9</option>
                        </select>
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="">Custom Select - Overlay - Validation Error</label>
                    <div class="input-box validation-error">
                        <select name="custom-select-right" class="ba-overlay" id="custom-select-right">
                            <option value="1">Select Magento Version</option>
                            <option value="2">Enterprise Edition 1.13</option>
                            <option value="3">Community Edition 1.8</option>
                            <option value="2">Enterprise Edition 1.14</option>
                            <option value="3">Community Edition 1.9</option>
                        </select>
                    </div>
                </div>
                <div class="field">
                    <label for="">Custom Select - Fullscreen - Validation Error</label>
                    <div class="input-box validation-error">
                        <select name="custom-select-right" class="ba-fullscreen" id="custom-select-right">
                            <option value="1">Select Magento Version</option>
                            <option value="2">Enterprise Edition 1.13</option>
                            <option value="3">Community Edition 1.8</option>
                            <option value="2">Enterprise Edition 1.14</option>
                            <option value="3">Community Edition 1.9</option>
                        </select>
                    </div>
                </div>
                <div class="field validation-error">
                    <label for="custom-select" class="required"><em>*</em>Fullscreen Thumbnail Select - Validation Error</label>
                    <div class="input-box">
                        <select id="custom-select" name="custom-select" title="Custom Select" class="validate-select required-entry ba-fullthumb">
                            <option value="" data-color="#fff">Pick Your Favorite Color</option>
                            <option value="1" data-color="#4A90E2">Leonardo</option>
                            <option value="2" data-color="#F5A623">Michelangelo</option>
                            <option value="3" data-color="#9013FE">Donatello</option>
                            <option value="999" data-color="#D0021B">Raphael</option>
                            <option value="4" data-color="#8B572A">Splinter</option>
                            <option value="5" data-color="#F8E71C">April O'Neil</option>
                            <option value="6" data-color="#B8E986">Casey Jones</option>
                            <option value="7" data-color="#9B9B9B">Shredder</option>
                            <option value="8" data-color="#003263">Karai</option>
                            <option value="10" data-color="#B09CBD">Baxter</option>
                            <option value="11" data-color="#D6A2AA">Krang</option>
                            <option value="12" data-color="#933123">Beabop</option>
                            <option value="13" data-color="#9B9B9B">Rocksteady</option>
                            <option value="14" data-color="#14B97F">Leatherhead</option>
                        </select>
                    </div>
                </div>
            </li>
        </ul>
    </form>
</section>